/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BreadcrumbNav: typeof import('./../components/BreadcrumbNav/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    MarkdownReply: typeof import('./../components/MarkdownReply/index.vue')['default']
    OverflowText: typeof import('./../components/OverflowText/index.vue')['default']
    PageHeader: typeof import('./../components/PageHeader/index.vue')['default']
    Redirect: typeof import('./../components/Redirect/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouteView: typeof import('./../components/RouteView/index.vue')['default']
  }
}
